#include "CarSchema.h"

namespace flasc {
namespace CarSchema {

const std::vector<FieldSpec>& Fields() {
    static const std::vector<FieldSpec> fields = {
    {"floatAsInt_A", "masterVolume", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_E", "MaxConeAttenuation", FieldKind::Int32, ValueRule::Scale100},
    {"engineLowSound", "lowEngineLoop", FieldKind::Hash, ValueRule::Raw},
    {"engineHighSound", "highEngineLoop", FieldKind::Hash, ValueRule::Raw},
    {"exhaustLowSound", "lowExhaustLoop", FieldKind::Hash, ValueRule::Raw},
    {"exhaustHighSound", "highExhaustLoop", FieldKind::Hash, ValueRule::Raw},
    {"revsOffSound", "revsOffLoop", FieldKind::Hash, ValueRule::Raw},
    {"field_26", "EngineAccelVolume", FieldKind::Float, ValueRule::Raw},
    {"field_2A", "ExhaustAccelVolume", FieldKind::Float, ValueRule::Raw},
    {"floatAsInt_2E", "EngineAccelMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_32", "EngineAccelMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"field_36", "EngineDecelVolume", FieldKind::Float, ValueRule::Raw},
    {"field_3A", "ExhaustDecelVolume", FieldKind::Float, ValueRule::Raw},
    {"floatAsInt_3E", "EngineDecelMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_42", "EngineDecelMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"field_46", "EngineIdleVolume", FieldKind::Float, ValueRule::Raw},
    {"field_4A", "ExhaustIdleVolume", FieldKind::Float, ValueRule::Raw},
    {"floatAsInt_4E", "EngineIdleMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_52", "EngineIdleMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"field_56", "EngineRevsVolume", FieldKind::Float, ValueRule::Raw},
    {"field_5A", "ExhaustRevsVolume", FieldKind::Float, ValueRule::Raw},
    {"floatAsInt_5E", "EngineRevsMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_62", "EngineRevsMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_66", "ThrottleResonanceVolume", FieldKind::Int32, ValueRule::Scale100},
    {"field_6A", "Filter1Cutoff", FieldKind::Float, ValueRule::Raw},
    {"field_6E", "Filter2Cutoff", FieldKind::Float, ValueRule::Raw},
    {"floatAsInt_72", "ResonanceMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_76", "ResonanceMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"engineWaveShape", "EngineSynthDef", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_7E", "EngineWaveShapePitch", FieldKind::Int32, ValueRule::Scale100},
    {"exhaustWaveShape", "ExhaustSynthDef", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_86", "ExhaustWaveShapePitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_multiplier1200_8A", "MinPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"floatAsInt_multiplier1200_8E", "MaxPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"engineIdleLoopSound", "engineIdleLoopSound", FieldKind::Hash, ValueRule::Raw},
    {"exhaustIdleLoopSound", "exhaustIdleLoopSound", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_multiplier1200_9A", "IdleMinPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"floatAsInt_multiplier1200_9E", "IdleMaxPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"transmissionSound", "transmissionSound", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_A6", "TransWhineMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_AA", "TransWhineMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"sound_AE", "InductionLoop", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_B2", "InductionMinPitch", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_B6", "InductionMaxPitch", FieldKind::Int32, ValueRule::Scale100},
    {"exhaustPopSound", "exhaustPopSound", FieldKind::Hash, ValueRule::Raw},
    {"airIntakeSound", "TurboWhine", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_multiplier1200_C2", "TurboMinPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"floatAsInt_multiplier1200_C6", "TurboMaxPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"dumpValveSound", "dumpValveSound", FieldKind::Hash, ValueRule::Raw},
    {"startSound", "startupRevs", FieldKind::Hash, ValueRule::Raw},
    {"hornSound", "hornSounds", FieldKind::Hash, ValueRule::Raw},
    {"openSound", "doorOpenSound", FieldKind::Hash, ValueRule::Raw},
    {"closeSound", "doorCloseSound", FieldKind::Hash, ValueRule::Raw},
    {"trunkOpenSound", "bootOpenSound", FieldKind::Hash, ValueRule::Raw},
    {"trunkCloseSound", "bootCloseSound", FieldKind::Hash, ValueRule::Raw},
    {"field_E6", "BrakeSqueekFactor", FieldKind::Float, ValueRule::Raw},
    {"suspensionUpSound", "suspensionUpSound", FieldKind::Hash, ValueRule::Raw},
    {"suspensionDownSound", "suspensionDownSound", FieldKind::Hash, ValueRule::Raw},
    {"field_F2", "minSuspCompThresh", FieldKind::Float, ValueRule::Raw},
    {"field_F6", "maxSuspCompThresh", FieldKind::Float, ValueRule::Raw},
    {"policeScannerManufacturerSound", "policeScannerManufacturerSound", FieldKind::Hash, ValueRule::Raw},
    {"policeScannerModelSound", "policeScannerModelSound", FieldKind::Hash, ValueRule::Raw},
    {"policeScannerVehicleCategorySound", "policeScannerVehicleCategorySound", FieldKind::Hash, ValueRule::Raw},
    {"gearTransmissionSound", "gearTransmissionSound", FieldKind::Hash, ValueRule::Raw},
    {"floatAsInt_multiplier1200_10A", "GearTransMinPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"floatAsInt_multiplier1200_10E", "GearTransMaxPitch", FieldKind::Int32, ValueRule::Scale1200},
    {"floatAsInt_multiplier1200_112", "GTThrottleVol", FieldKind::Int32, ValueRule::Scale1200},
    {"floatAsInt_116", "DumpValveProb", FieldKind::Int32, ValueRule::Scale100},
    {"field_11A", "TurboSpinUpSpeed", FieldKind::Int32, ValueRule::Raw},
    {"floatAsInt_11E", "VolumeBoost", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_122", "ExhaustBoost", FieldKind::Int32, ValueRule::Scale100},
    {"floatAsInt_126", "TransmissionBoost", FieldKind::Int32, ValueRule::Scale100},
    {"jumpLandSound", "jumpLandSound", FieldKind::Hash, ValueRule::Raw},
    {"field_12E", "JumpLandMinThresh", FieldKind::Int32, ValueRule::Raw},
    {"field_132", "JumpLandMaxThresh", FieldKind::Int32, ValueRule::Raw},
    {"ignitionSound", "ignitionSound", FieldKind::Hash, ValueRule::Raw},
    {"engineShutDownSound", "engineShutDownSound", FieldKind::Hash, ValueRule::Raw},
    {"field_13E", "VolumeCategory", FieldKind::Int8, ValueRule::Raw},
    {"field_13F", "GPSType", FieldKind::Int8, ValueRule::Raw},
    {"field_140", "RadioType", FieldKind::Int8, ValueRule::Raw},
    {"field_141", "RadioGenre", FieldKind::Int8, ValueRule::Raw},
    {"indicatorVehicleOn", "indicatorOnSound", FieldKind::Hash, ValueRule::Raw},
    {"indicatorVehicleOff", "indicatorOffSound", FieldKind::Hash, ValueRule::Raw},
    {"engineCoolingFan", "coolingFanSound", FieldKind::Hash, ValueRule::Raw},
    {"handbrakeSound_14E", "handbrakeSound2", FieldKind::Hash, ValueRule::Raw},
    {"sound_152", "nullSound2", FieldKind::Hash, ValueRule::Raw},
    {"sound_156", "nullSound3", FieldKind::Hash, ValueRule::Raw},
    {"handbrakeSound_15A", "handbrakeSound", FieldKind::Hash, ValueRule::Raw},
    {"field_15E", "GpsVoice", FieldKind::Int16, ValueRule::PackedInt16Lo},
    {"field_15F", "GpsVoice", FieldKind::Int16, ValueRule::PackedInt16Hi},
    {"field_160", "RadioLeakage", FieldKind::Int8, ValueRule::Raw},
    };
    return fields;
}

} // namespace CarSchema
} // namespace flasc
